[project]
name = "uaiot_mp_esp_controller"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "adafruit-ampy>=1.1.0",
    "esptool>=5.1.0",
    "mpremote>=1.26.1",
]
